project/django_video/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('video_app.urls')),
    path('login/', include('login.urls'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

project/login/urls.py
from login import views
from django.urls import path


urlpatterns = [
    path('login', views.CustomLoginView.as_view(), name='login-page'),
    path('register', views.RegistrationView.as_view(), name='register-page'),
    path('account/<int:pk>', views.CustomAccountView.as_view(), name='account-page'),
    path('logout', views.logout_view, name='logout-page')
]

project/video_app/urls.py
from video_app import views
from django.urls import path


urlpatterns = [
    path('', views.root_page),
    path('main/', views.main_page, name='main-page'),
    path('hr_main/', views.hr_main_view, name='hr-page')
]

project/login/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from django.utils.translation import gettext_lazy as _
from .managers import CustomUserManager
from django.db.models import Q
from django.apps import apps


class CustomUser(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(_("email address"), unique=True)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    first_name = models.CharField(max_length=40, null=True)
    last_name = models.CharField(max_length=40, null=True)
    patronymic = models.CharField(max_length=40, null=True)

    USERNAME_FIELD = 'email'

    objects = CustomUserManager()

    def __str__(self):
        return self.email


class HR(models.Model):
    user = models.OneToOneField('CustomUser', on_delete=models.CASCADE, primary_key=True)


class Applicant(models.Model):
    user = models.OneToOneField('CustomUser', on_delete=models.CASCADE, primary_key=True)

project/video_app/models.py
from django.db import models
from pgvector.django import VectorField


class Video(models.Model):
    file = models.FileField()
    vector = VectorField(dimensions=6)
    cluster = models.SmallIntegerField()


class Personality(models.Model):
    name = models.CharField(max_length=40)
    group = models.ForeignKey('PersonalityGroup', on_delete=models.CASCADE)

    def __str__(self):
        return self.name
    

class PersonalityGroup(models.Model):
    name = models.CharField(max_length=40)

    def __str__(self):
        return self.name

project/login/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from .models import CustomUser


class CustomUserCreationForm(UserCreationForm):

    class Meta:
        model = CustomUser
        fields = ("email", "is_superuser")
        labels = {
            "email": "Электронная почта",
            "is_superuser": "Аккаунт для HR?",
            "password1": "Пароль",
            "password2": "Подтверждение пароля",
            "password": "Пароль"
        }
        help_texts = {
            "is_superuser": "ЗАГЛУШКА",
        }


class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = CustomUser
        fields = ("first_name", "last_name", "patronymic")

project/video_app/forms.py
from django import forms


class UploadFileForm(forms.Form):
    file = forms.FileField(label='Загрузите файл:')

project/login/views.py
from django.http.request import HttpRequest as HttpRequest
from django.shortcuts import render
from .forms import CustomUserCreationForm, CustomUserChangeForm
from .models import CustomUser
from django.views.generic.edit import CreateView, UpdateView
from django.urls import reverse_lazy
from django.shortcuts import render, redirect
from django.contrib.auth.views import LoginView
from django.contrib.auth import logout, login, authenticate

class RegistrationView(CreateView):
    form_class = CustomUserCreationForm
    model = CustomUser
    template_name = 'login/register.html'

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)

        return redirect(reverse_lazy('account-page',
                               kwargs={'pk': user.pk}))


class CustomLoginView(LoginView):
    template_name = 'login/login.html'
    next_page = reverse_lazy('main-page')


class CustomAccountView(UpdateView):
    template_name = 'login/account.html'
    form_class = CustomUserChangeForm
    model = CustomUser
    
    def form_valid(self, form):
        print(form.cleaned_data)
        user = form.save()

        return redirect(reverse_lazy('account-page',
                               kwargs={'pk': user.pk}))
    

def logout_view(request):
    logout(request)
    return redirect(reverse_lazy('login-page'))

project/video_app/views.py
import json
import time
import base64

from django.shortcuts import render, redirect
from django.urls import reverse, reverse_lazy
from django.http import HttpRequest, HttpResponseRedirect, HttpResponse
from .models import Video, PersonalityGroup, Personality
from .forms import UploadFileForm
from django.contrib.auth.decorators import user_passes_test
from . import utils
from . import tasks


def root_page(request: HttpRequest):
    if not request.user.is_authenticated:
        return redirect(reverse_lazy('login-page'))
    return redirect(reverse_lazy('main-page'))


def main_page(request: HttpRequest):
    if request.user.is_superuser:
        return redirect(reverse_lazy('hr-page'))
    if request.method == 'POST':
        form = UploadFileForm(request.POST, request.FILES)
        if form.is_valid():
            file = request.FILES['file'].read()
            byte = base64.b64encode(file)

            data = {'file': byte.decode('utf-8'),
                    'name': request.FILES['file'].name}

            # tasks.task_upload_file.delay(data=data)
            Video.objects.create(file=file)
            return HttpResponse('Fine')
    else:
        form = UploadFileForm()
    return render(request, 'video_app/index.html', {'form': form,
                                                    'groups': PersonalityGroup.objects.all()})


@user_passes_test(lambda u: u.is_superuser)
def hr_main_view(request):
    personality_rows = [Personality.objects.all()[i::4] for i in range(4)]
    return render(request, 'video_app/hr_main.html',
                  {'groups': PersonalityGroup.objects.all(),
                   'personality_rows': personality_rows})

project/login/templates/login/account.html
{% extends 'video_app/base.html' %}
{% block main %}
{{ form.errors }}
<form method="post">
    {% csrf_token %}
    {% for field in form %}
    <div>
        <label> {{ field.label }}</label>
        <p>{{ field }}</p>
    </div>
    {% endfor %}
    <button type="submit">Зарегистрироваться</button>
</form>
{% endblock %}

project/login/templates/login/login.html
{% extends 'video_app/base.html' %}
{% block main %}
Ur fucked suck dick
{% endblock %}

project/login/templates/login/register.html
{% extends 'video_app/base.html' %}
{% block main %}
{{ form.errors }}
<form method="post">
    {% csrf_token %}
    {% for field in form %}
    <div>
        {% if field != form.password %}
            <label> {{ field.label }}</label>
            <p>{{ field }}</p>
        {% endif %}
    </div>
    {% endfor %}
    <button type="submit">Обновить данные</button>
</form>
{% endblock %}

project/video_app/templates/video_app/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport"
              content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
        <link rel="stylesheet" href="{% static 'video_app/css/styles.css' %}">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>


    </head>
    <body>
        {% block header %}
        {% include 'video_app/header.html' %}
        {% endblock %}
        {% block main %}
        
        {% endblock %}
        {% block footer %}
        
        {% endblock %}
    </body>
    <script src="{% static 'video_app/js/script.js' %}"></script>
</html>

project/video_app/templates/video_app/header.html
{% if user.is_authenticated %}
<nav class="navbar navbar-expand-lg sticky-top navbar-light bg-light">
    <a class="navbar-brand" href="#">Person Scout</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" href="url 'main-page'">Главная <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Личный кабинет
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <a class="dropdown-item" href="{% url 'account-page' pk=user.id%}">Управление личным кабинетом</a>
            <a class="dropdown-item" href="{% url 'logout-page'%}">Выйти</a>
          </div>
        </li>
      </ul>
    </div>
  </nav>
{% endif %}

project/video_app/templates/video_app/hr_main.html
{% extends 'video_app/base.html' %}
{% load static %}
{% block main %}
<div>
    <table class="table">
        <thead>
            <tr>
                {% for g in groups %}
                <th scope="col">{{ g }}</th>
                {% endfor %}
            </tr>
        </thead>
        <tbody>
            {% for row in personality_rows %}
            <tr>
                {% for p in row %}
                    <td>{{ p }}</td>
                {% endfor %}
            </tr>
            {% endfor %}
        </tbody>
        <!-- <tr>
            {% for g in groups %}
            <th>{{ g }}</th>
            {% endfor %}
        </tr> -->
    </table>
</div>
{% endblock %}

project/video_app/templates/video_app/index.html
{% extends 'video_app/base.html' %}
{% load static %}
{% block main %}
<div class="mainText">
    Загрузите видео в эту форму
</div>
<div>
    <form enctype="multipart/form-data" action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="progress-wrapper">
            <div id="progress-bar-file" class="progress"> </div>
        </div>
        <button type="button" onclick="postFile()">Отправить</button>
    </form>
</div>
<div>
    <table>
        <tbody class="table">
            {% for g in groups %}
            <tr class="table-row">
                <td class="table-elem">{{ g }}</td>
                {% for p in g.personality_set.all %}
                    <td class="table-elem">{{ p }}</td>
                {% endfor %}
            </tr>
            {% endfor %}
        </tbody>
        <!-- <tr>
            {% for g in groups %}
            <th>{{ g }}</th>
            {% endfor %}
        </tr> -->
    </table>
</div>
{% endblock %}